import type { MigrationInterface, QueryRunner } from 'typeorm';

export class RefactorProductPrice1763647677731 implements MigrationInterface {
    name = 'RefactorProductPrice1763647677731'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "keys" DROP CONSTRAINT IF EXISTS "FK_keys_orderItemId"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT IF EXISTS "order_items_orderId_fkey"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT IF EXISTS "FK_af929a5f2a400fdb6913b4967e1"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_keys_orderItemId"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_keys_createdAt"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_order_items_orderId"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_payments_externalId"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_payments_orderId"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_payments_status"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_payments_createdAt"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_payments_orderId_status"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_users_email"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_users_emailConfirmed_createdAt"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_orders_kinguinReservationId"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_orders_createdAt"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_webhook_logs_externalId"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_webhook_logs_externalId_webhookType_createdAt"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_webhook_logs_orderId_createdAt"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_webhook_logs_webhookType_processed_createdAt"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_audit_logs_adminUserId_createdAt"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_audit_logs_action_createdAt"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_audit_logs_target_createdAt"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_email_bounces_email_type"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_email_bounces_type_createdAt"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_email_bounces_bouncedAt"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_email_bounces_email"`);
        await queryRunner.query(`CREATE TABLE "product_offers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "provider" character varying(30) NOT NULL, "providerSku" character varying(100) NOT NULL, "stock" integer, "costMinor" bigint NOT NULL, "currency" character(3) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "lastSeenAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5acf99c4c02b2a7129c80278971" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_4b6427e4ef8acb2e39c797c170" ON "product_offers" ("provider", "providerSku") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_2014aa7948a514d4e967d1c1c6" ON "product_offers" ("productId", "isActive", "costMinor") `);
        await queryRunner.query(`CREATE TYPE "public"."dynamic_pricing_rules_rule_type_enum" AS ENUM('margin_percent', 'fixed_markup', 'floor_cap', 'dynamic_adjust')`);
        await queryRunner.query(`CREATE TABLE "dynamic_pricing_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "rule_type" "public"."dynamic_pricing_rules_rule_type_enum" NOT NULL, "marginPercent" numeric(5,2), "fixedMarkupMinor" bigint, "floorMinor" bigint, "capMinor" bigint, "priority" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e29278876ae21cd70285a7edb15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_1ad8fa39b15d035f6861032258" ON "dynamic_pricing_rules" ("rule_type", "createdAt") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_bd617fb4f443059204ccc4bf35" ON "dynamic_pricing_rules" ("productId", "priority", "isActive") `);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "externalId" character varying(100), "slug" text NOT NULL, "title" text NOT NULL, "subtitle" text, "description" text, "platform" character varying(50), "region" character varying(50), "drm" character varying(50), "ageRating" character varying(10), "category" character varying(50), "isCustom" boolean NOT NULL DEFAULT false, "isPublished" boolean NOT NULL DEFAULT false, "cost" numeric(20,8) NOT NULL DEFAULT '0.00000000', "currency" character(3) NOT NULL DEFAULT 'EUR', "price" numeric(20,8) NOT NULL DEFAULT '0.00000000', "priceVersion" integer NOT NULL DEFAULT '0', "rating" numeric(3,2), "reviewCount" integer NOT NULL DEFAULT '0', "searchTsv" tsvector, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_464f927ae360106b783ed0b4106" UNIQUE ("slug"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_f3488244cc1218c9ec7f375b31" ON "products" ("category", "isPublished") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_464f927ae360106b783ed0b410" ON "products" ("slug") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_83e8372c6bb836cdeb9ad1811a" ON "products" ("platform", "region", "isPublished") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_5051a91d3cfff864bce11d940c" ON "products" ("isPublished", "price", "createdAt") `);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "total"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "totalCrypto" numeric(20,8) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`COMMENT ON COLUMN "keys"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "keys"."orderItemId" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "keys"."storageRef" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "keys"."viewedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "keys"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "keys"."updatedAt" IS NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "provider"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "provider" character varying NOT NULL DEFAULT 'nowpayments'`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "priceCurrency"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "priceCurrency" character varying`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "payCurrency"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "payCurrency" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_email_key"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "emailConfirmed" SET NOT NULL`);
        // Check if role column needs to be recreated with enum type
        const roleColumnResult = await queryRunner.query(`
          SELECT data_type FROM information_schema.columns 
          WHERE table_name = 'users' AND column_name = 'role'
        `);
        if (roleColumnResult.length === 0 || roleColumnResult[0].data_type !== 'USER-DEFINED') {
          await queryRunner.query(`ALTER TABLE "users" DROP COLUMN IF EXISTS "role"`);
          await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'admin'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
          await queryRunner.query(`ALTER TABLE "users" ADD "role" "public"."users_role_enum" NOT NULL DEFAULT 'user'`);
        }
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "status" character varying(20) NOT NULL DEFAULT 'created'`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."kinguinReservationId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "email_bounces" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."email_bounces_type_enum" AS ENUM('hard', 'soft', 'complaint')`);
        await queryRunner.query(`ALTER TABLE "email_bounces" ADD "type" "public"."email_bounces_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "email_bounces" ALTER COLUMN "bouncedAt" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_5f05cb8b95b8cce77494136d84" ON "keys" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_5620a12090f73a75e95b805a35" ON "keys" ("orderItemId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_af929a5f2a400fdb6913b4967e" ON "payments" ("orderId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_8277a466232344577740a61344" ON "payments" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_af929a5f2a400fdb6913b4967e" ON "payments" ("orderId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_c9ca05ceb7cc5eae113c2eb57c" ON "payments" ("externalId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_fba1f3dcf7fcac6097dc41416e" ON "users" ("emailConfirmed", "createdAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_d5e3786a82fe691d8bbbb1e256" ON "orders" ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_30e6836e8539f85bfc47198067" ON "orders" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_e333d71f02a96a05ef2721cfb2" ON "webhook_logs" ("externalId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_e7a1b6b9dfd0a2f12fe865c4b2" ON "webhook_logs" ("orderId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_d406ddb6432afc15a8a2032888" ON "webhook_logs" ("webhookType", "processed", "createdAt") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_12b49ba815e2def4044e3cf1a3" ON "webhook_logs" ("orderId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_c682834eb9285915769b397593" ON "webhook_logs" ("externalId", "webhookType", "createdAt") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_bb9ba5a42e22da6341a26220e8" ON "audit_logs" ("adminUserId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_4553ee67b6b7c4b980994c5c1f" ON "audit_logs" ("target", "createdAt") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_0ec936941eb8556fcd7a1f0eae" ON "audit_logs" ("action", "createdAt") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_92b5066272b47b2415180e1348" ON "audit_logs" ("adminUserId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_edb169f480d692e8fa3325af1a" ON "email_bounces" ("email") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_21c315b8f0fee9b9d35dccb596" ON "email_bounces" ("bouncedAt") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_30cd7f10ce4ba49d3fd605b82f" ON "email_bounces" ("type", "createdAt") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_db185f121ed5bc2c216b14afd5" ON "email_bounces" ("email", "type") `);
        await queryRunner.query(`ALTER TABLE "keys" ADD CONSTRAINT "FK_5620a12090f73a75e95b805a352" FOREIGN KEY ("orderItemId") REFERENCES "order_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_af929a5f2a400fdb6913b4967e1" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_offers" ADD CONSTRAINT "FK_9cbedcf16abd5715a1b84686531" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dynamic_pricing_rules" ADD CONSTRAINT "FK_e3c819d04f96e8c3ca1d3741593" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "dynamic_pricing_rules" DROP CONSTRAINT "FK_e3c819d04f96e8c3ca1d3741593"`);
        await queryRunner.query(`ALTER TABLE "product_offers" DROP CONSTRAINT "FK_9cbedcf16abd5715a1b84686531"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_af929a5f2a400fdb6913b4967e1"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "keys" DROP CONSTRAINT "FK_5620a12090f73a75e95b805a352"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db185f121ed5bc2c216b14afd5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30cd7f10ce4ba49d3fd605b82f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21c315b8f0fee9b9d35dccb596"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_edb169f480d692e8fa3325af1a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92b5066272b47b2415180e1348"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ec936941eb8556fcd7a1f0eae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4553ee67b6b7c4b980994c5c1f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb9ba5a42e22da6341a26220e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c682834eb9285915769b397593"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12b49ba815e2def4044e3cf1a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d406ddb6432afc15a8a2032888"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7a1b6b9dfd0a2f12fe865c4b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e333d71f02a96a05ef2721cfb2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30e6836e8539f85bfc47198067"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5e3786a82fe691d8bbbb1e256"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fba1f3dcf7fcac6097dc41416e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9ca05ceb7cc5eae113c2eb57c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af929a5f2a400fdb6913b4967e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8277a466232344577740a61344"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af929a5f2a400fdb6913b4967e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5620a12090f73a75e95b805a35"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f05cb8b95b8cce77494136d84"`);
        await queryRunner.query(`ALTER TABLE "email_bounces" ALTER COLUMN "bouncedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "email_bounces" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."email_bounces_type_enum"`);
        await queryRunner.query(`ALTER TABLE "email_bounces" ADD "type" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."kinguinReservationId" IS 'Kinguin reservation ID for tracking fulfillment status'`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('created', 'waiting', 'confirming', 'paid', 'underpaid', 'failed', 'fulfilled')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "status" "public"."orders_status_enum" NOT NULL DEFAULT 'created'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "emailConfirmed" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "payCurrency"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "payCurrency" character varying(10)`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "priceCurrency"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "priceCurrency" character varying(10)`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "provider"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "provider" character varying(50) NOT NULL DEFAULT 'nowpayments'`);
        await queryRunner.query(`COMMENT ON COLUMN "keys"."updatedAt" IS 'When key record was last updated'`);
        await queryRunner.query(`COMMENT ON COLUMN "keys"."createdAt" IS 'When key record was created'`);
        await queryRunner.query(`COMMENT ON COLUMN "keys"."viewedAt" IS 'When customer viewed/revealed the key'`);
        await queryRunner.query(`COMMENT ON COLUMN "keys"."storageRef" IS 'R2 object key where encrypted key is stored'`);
        await queryRunner.query(`COMMENT ON COLUMN "keys"."orderItemId" IS 'Foreign key to order_items'`);
        await queryRunner.query(`COMMENT ON COLUMN "keys"."id" IS 'Unique identifier for key record'`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "totalCrypto"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "total" numeric(20,8) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5051a91d3cfff864bce11d940c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_83e8372c6bb836cdeb9ad1811a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_464f927ae360106b783ed0b410"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3488244cc1218c9ec7f375b31"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd617fb4f443059204ccc4bf35"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ad8fa39b15d035f6861032258"`);
        await queryRunner.query(`DROP TABLE "dynamic_pricing_rules"`);
        await queryRunner.query(`DROP TYPE "public"."dynamic_pricing_rules_rule_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2014aa7948a514d4e967d1c1c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b6427e4ef8acb2e39c797c170"`);
        await queryRunner.query(`DROP TABLE "product_offers"`);
        await queryRunner.query(`CREATE INDEX "IDX_email_bounces_email" ON "email_bounces" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_email_bounces_bouncedAt" ON "email_bounces" ("bouncedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_email_bounces_type_createdAt" ON "email_bounces" ("type", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_email_bounces_email_type" ON "email_bounces" ("email", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_target_createdAt" ON "audit_logs" ("target", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_action_createdAt" ON "audit_logs" ("action", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_adminUserId_createdAt" ON "audit_logs" ("adminUserId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_webhook_logs_webhookType_processed_createdAt" ON "webhook_logs" ("webhookType", "processed", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_webhook_logs_orderId_createdAt" ON "webhook_logs" ("orderId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_webhook_logs_externalId_webhookType_createdAt" ON "webhook_logs" ("externalId", "webhookType", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_webhook_logs_externalId" ON "webhook_logs" ("externalId") `);
        await queryRunner.query(`CREATE INDEX "IDX_orders_createdAt" ON "orders" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_orders_kinguinReservationId" ON "orders" ("kinguinReservationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_emailConfirmed_createdAt" ON "users" ("emailConfirmed", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_orderId_status" ON "payments" ("orderId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_createdAt" ON "payments" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_status" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_orderId" ON "payments" ("orderId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_payments_externalId" ON "payments" ("externalId") `);
        await queryRunner.query(`CREATE INDEX "IDX_order_items_orderId" ON "order_items" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_keys_createdAt" ON "keys" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_keys_orderItemId" ON "keys" ("orderItemId") `);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_af929a5f2a400fdb6913b4967e1" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "order_items_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "keys" ADD CONSTRAINT "FK_keys_orderItemId" FOREIGN KEY ("orderItemId") REFERENCES "order_items"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
