import { IsString, IsEnum, IsOptional, IsNumber } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

/**
 * Kinguin Webhook Payload DTO
 *
 * Validates incoming webhooks from Kinguin for order delivery notifications.
 *
 * Webhook is triggered when:
 * - Order is ready (status='ready', includes key)
 * - Order fails (status='failed', includes error)
 * - Order is cancelled (status='cancelled')
 *
 * @example
 * {
 *   "reservationId": "res-12345",
 *   "status": "ready",
 *   "key": "XXXXX-XXXXX-XXXXX-XXXXX",
 *   "timestamp": 1730000000000
 * }
 *
 * @see KinguinController.handleWebhook() - Uses this DTO for validation
 */
export class WebhookPayloadDto {
  /**
   * Kinguin reservation/order ID
   *
   * Unique identifier for the order reservation made via reserve() call.
   * Used to link webhook back to original order in database.
   *
   * @example "res-12345"
   */
  @ApiProperty({
    description: 'Kinguin reservation ID',
    example: 'res-12345',
  })
  @IsString()
  reservationId!: string;

  /**
   * Current order fulfillment status
   *
   * Possible values:
   * - waiting: Order created, awaiting processing
   * - processing: Kinguin is fulfilling the order
   * - ready: Order complete, key available (terminal success)
   * - failed: Order failed (terminal error)
   * - cancelled: Order cancelled by user/admin (terminal cancelled)
   *
   * Terminal states (ready/failed/cancelled) should not transition further.
   *
   * @example "ready"
   */
  @ApiProperty({
    description: 'Order fulfillment status',
    enum: ['waiting', 'processing', 'ready', 'failed', 'cancelled'],
    example: 'ready',
  })
  @IsEnum(['waiting', 'processing', 'ready', 'failed', 'cancelled'])
  status!: 'waiting' | 'processing' | 'ready' | 'failed' | 'cancelled';

  /**
   * License key (only present when status='ready')
   *
   * The actual game key or license key delivered by Kinguin.
   * Only populated when order is successfully fulfilled.
   * Should NOT be present for other statuses.
   *
   * @example "XXXXX-XXXXX-XXXXX-XXXXX"
   */
  @ApiProperty({
    description: 'License key (only when status=ready)',
    example: 'XXXXX-XXXXX-XXXXX-XXXXX',
    required: false,
  })
  @IsString()
  @IsOptional()
  key?: string;

  /**
   * Error message (only present when status='failed')
   *
   * Describes why the order failed.
   * Only populated when order fails.
   * Should NOT be present for other statuses.
   *
   * @example "Out of stock"
   */
  @ApiProperty({
    description: 'Error message (only when status=failed)',
    example: 'Out of stock',
    required: false,
  })
  @IsString()
  @IsOptional()
  error?: string;

  /**
   * Webhook timestamp (Unix milliseconds)
   *
   * When the webhook was generated by Kinguin.
   * Used to detect out-of-order deliveries and clock skew.
   *
   * @example 1730000000000
   */
  @ApiProperty({
    description: 'Webhook timestamp (Unix milliseconds)',
    example: 1730000000000,
    required: false,
  })
  @IsNumber()
  @IsOptional()
  timestamp?: number;
}
